// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsy_pLZjY0t5DBKS0WmRr6ZwIYoqbMx8Q',
    appId: '1:144404261090:web:f085c076fc4e24aef916bb',
    messagingSenderId: '144404261090',
    projectId: 'myprojectbmc1-ff2a6',
    authDomain: 'myprojectbmc1-ff2a6.firebaseapp.com',
    storageBucket: 'myprojectbmc1-ff2a6.firebasestorage.app',
    measurementId: 'G-JYDPVHMX7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUAYawt_kQQcW6tiog0lzf9xuNz7_X-C4',
    appId: '1:144404261090:android:58bed2c1f766000ef916bb',
    messagingSenderId: '144404261090',
    projectId: 'myprojectbmc1-ff2a6',
    storageBucket: 'myprojectbmc1-ff2a6.firebasestorage.app',
  );
}
